# Generated by Django 3.0.7 on 2020-12-31 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201227_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuse',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
