# Generated by Django 3.0.7 on 2020-12-31 22:33

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201231_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterevent',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='event',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eligible_attendees',
            field=models.ManyToManyField(blank=True, default=dashboard.models.all_actives_and_candidates, related_name='_event_eligible_attendees_+', to='dashboard.Brother'),
        ),
    ]
