# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_healthandsafteyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('storage', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
                ('cal_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='healthandsafteyevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='healthandsafteyevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='scholarshipevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Calendar'),
        ),
    ]
