from dashboard.views._positions._ec._marshal import *
from dashboard.views._positions._ec._president import *
from dashboard.views._positions._ec._recruitment_chair import *
from dashboard.views._positions._ec._scholarship_chair import *
from dashboard.views._positions._ec._secretary import *
from dashboard.views._positions._ec._treasurer import *
from dashboard.views._positions._ec._vice_president import *
from dashboard.views._positions._ec._vphs import *
from dashboard.views._positions._ec._add_brother import *
